lenguage: php
dist: xenial
 php:
   -"7.0"
 env:
  -80==pgsql
before_install:
 -sudo apt-get update -q
install: ./install-dependencies.sh
before_script: true

script:
  - phpunit test.php
notifications:
  email:
  - darwin78@hotmail.com

